name: ApiPlugin
version: '1.0-SNAPSHOT'
main: me.porion.apiplugin.ApiPlugin
api-version: 1.19
commands:
  setupApi:
    description: Setup the api within your server
    usage: /<command>
    aliases: setupApi